spring:
  datasource:
    url: jdbc:mysql://qianfeng1.qfjava.cn:8300/ublog?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: qishimeiyoumima
    type: com.alibaba.druid.pool.DruidDataSource #连接池的类型
  redis:
    host: qianfeng1.qfjava.cn
    port: 8400
    password: redis001
#注意如果你在mybatis 的xml文件中也配置了pagehelper,这里也配置了,会出现配置冲突的可能性,使用的时候会抛出异常,提示出现了两个pagehleper
pagehelper:
  helper-dialect: mysql #不同的数据库分页语句可能不一样,
  params: count=countsql
  reasonable: true
  support-methods-arguments: true