spring:
  datasource:
    username: root
    password: qishimeiyoumima
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://qianfeng1.qfjava.cn:8300/ublog?useUnicode=true&characterEncoding=utf8
  redis:
    host: qianfeng1.qfjava.cn
    port: 8400
    password: redis001
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
